services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: stash_db
      POSTGRES_USER: stash_user
      POSTGRES_PASSWORD: stash_pw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
volumes:
  pgdata:
