"""Performer to stash box ids

Revision ID: 02713bef922e
Revises: 82be0c176fe1
Create Date: 2025-01-10 23:15:40.227071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02713bef922e'
down_revision: Union[str, None] = '82be0c176fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performer_stash_box',
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.Column('stash_box_id', sa.String(), nullable=False),
    sa.Column('stash_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['performer_id'], ['performer.id'], ),
    sa.ForeignKeyConstraint(['stash_box_id'], ['stash_box.id'], ),
    sa.PrimaryKeyConstraint('performer_id', 'stash_box_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performer_stash_box')
    # ### end Alembic commands ###
