"""Add face statu

Revision ID: 13b0f2373f06
Revises: c3e881fbcc9b
Create Date: 2025-01-20 03:08:42.697485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b0f2373f06'
down_revision: Union[str, None] = 'c3e881fbcc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deepface_face', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('DISCOVERED', 'CONFIRMED', 'DISCARD', name='facestatus'), server_default='DISCOVERED', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deepface_face', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
