"""Img, ImgFile

Revision ID: 4690ad47d24a
Revises: c4be50578cbd
Create Date: 2025-01-16 17:38:05.911161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4690ad47d24a'
down_revision: Union[str, None] = 'c4be50578cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('phash', sa.String(), nullable=False),
    sa.Column('image_type', sa.Enum('STASH_BOX_PERFORMER', 'PERFORMER_MAIN', 'SCENE_FRAME', 'FACE', 'BODY', name='imagetype'), nullable=False),
    sa.Column('external_uri', sa.String(), nullable=True),
    sa.Column('performer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['performer_id'], ['performer.id'], ),
    sa.PrimaryKeyConstraint('phash')
    )
    op.create_table('image_file',
    sa.Column('phash', sa.String(), nullable=False),
    sa.Column('scale', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phash'], ['image.phash'], ),
    sa.PrimaryKeyConstraint('phash', 'scale')
    )
    #Force a refresh of all performers
    op.execute('UPDATE performer SET stash_updated_at = null')      
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_file')
    op.drop_table('image')
    # ### end Alembic commands ###
