"""Images

Revision ID: 64782571f628
Revises: c4be50578cbd
Create Date: 2025-01-17 00:53:12.389924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64782571f628'
down_revision: Union[str, None] = 'c4be50578cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('phash', sa.String(), nullable=False),
    sa.Column('image_type', sa.Enum('STASH_BOX_PERFORMER', 'PERFORMER_MAIN', 'SCENE_FRAME', 'FACE', 'BODY', name='imagetype'), nullable=False),
    sa.Column('original_scale', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('phash')
    )
    op.create_table('image_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phash', sa.String(), nullable=False),
    sa.Column('scale', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phash'], ['image.phash'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phash', 'scale', name='uq_image_file_phash_scale')
    )
    op.create_table('image_uri',
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('image_pash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['image_pash'], ['image.phash'], ),
    sa.PrimaryKeyConstraint('uri')
    )
    op.create_table('performers_images',
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.Column('image_phash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['image_phash'], ['image.phash'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['performer.id'], ),
    sa.PrimaryKeyConstraint('performer_id', 'image_phash')
    )
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image_phash', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_image', 'image', ['main_image_phash'], ['phash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_image', type_='foreignkey')
        batch_op.drop_column('main_image_phash')

    op.drop_table('performers_images')
    op.drop_table('image_uri')
    op.drop_table('image_file')
    op.drop_table('image')
    # ### end Alembic commands ###
