"""Update stashbox data

Revision ID: 82be0c176fe1
Revises: 807700c3f24c
Create Date: 2025-01-10 21:40:22.326700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82be0c176fe1'
down_revision: Union[str, None] = '807700c3f24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stash_box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('api_key', sa.String(), nullable=False))
        batch_op.create_unique_constraint('uq_stash_box_endpoint_01', ['endpoint'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stash_box', schema=None) as batch_op:
        batch_op.drop_constraint('uq_stash_box_endpoint_01', type_='unique')
        batch_op.drop_column('api_key')
        batch_op.drop_column('endpoint')

    # ### end Alembic commands ###
