"""Performer Images from stash

Revision ID: 8b1e24280fa6
Revises: 6224179fd7ff
Create Date: 2025-01-11 01:27:58.812680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1e24280fa6'
down_revision: Union[str, None] = '6224179fd7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performer_stashbox_images',
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.Column('stash_box_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('phash', sa.String(), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['performer_id'], ['performer.id'], ),
    sa.ForeignKeyConstraint(['stash_box_id'], ['stash_box.id'], ),
    sa.PrimaryKeyConstraint('image_id', 'performer_id', 'stash_box_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performer_stashbox_images')
    # ### end Alembic commands ###
