"""Scene

Revision ID: 8ec5586705e8
Revises: 8b1e24280fa6
Create Date: 2025-01-14 16:46:25.593086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec5586705e8'
down_revision: Union[str, None] = '8b1e24280fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stash_updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('local_file_name', sa.String(), nullable=False),
    sa.Column('video_codec', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('downscale', sa.Integer(), nullable=True),
    sa.Column('downscale_width', sa.Integer(), nullable=True),
    sa.Column('downscale_height', sa.Integer(), nullable=True),
    sa.Column('relative_extract_dir', sa.String(), nullable=True),
    sa.Column('relative_downscale_extract_dir', sa.String(), nullable=True),
    sa.Column('relative_extract_face_dir', sa.String(), nullable=True),
    sa.Column('relative_downscale_extract_face_dir', sa.String(), nullable=True),
    sa.Column('hash_tolerance', sa.Integer(), nullable=True),
    sa.Column('nb_images', sa.Integer(), nullable=True),
    sa.Column('extraction_time', sa.Float(), nullable=True),
    sa.Column('face_detector', sa.String(), nullable=True),
    sa.Column('extends_face_detection', sa.Float(), nullable=True),
    sa.Column('nb_faces', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performers_scenes',
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['performer_id'], ['performer.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('performer_id', 'scene_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performers_scenes')
    op.drop_table('scene')
    # ### end Alembic commands ###
