"""ImageAnalysis DeepfaceFace

Revision ID: c3e881fbcc9b
Revises: a4867362c887
Create Date: 2025-01-17 14:31:40.129535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3e881fbcc9b'
down_revision: Union[str, None] = 'a4867362c887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_image_file_id', sa.Integer(), nullable=True),
    sa.Column('detector', sa.String(), nullable=False),
    sa.Column('expand_face', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['_image_file_id'], ['image_file.id'], name='fk_image_file'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deepface_face',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_image_analysis_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('gender_confidence', sa.Float(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('race_confidence', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('_performer_id', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('relative_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['_image_analysis_id'], ['image_analysis.id'], name='fk_image_analysis'),
    sa.ForeignKeyConstraint(['_performer_id'], ['performer.id'], name='fk_performer'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deepface_face')
    op.drop_table('image_analysis')
    # ### end Alembic commands ###
