"""Scene scale attribute

Revision ID: c4be50578cbd
Revises: 8ec5586705e8
Create Date: 2025-01-15 06:34:42.017020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4be50578cbd'
down_revision: Union[str, None] = '8ec5586705e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale', sa.Integer(), nullable=False, server_default='0'))
    #Not working at least with postgresql, probably not working at all
    #batch_op.execute('UPDATE scene SET scale = MAX(width, height)')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.drop_column('scale')

    # ### end Alembic commands ###
