"""Fix column overlapping, add enum to status

Revision ID: ebf6535f2ca8
Revises: 13b0f2373f06
Create Date: 2025-01-20 07:32:16.464998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf6535f2ca8'
down_revision: Union[str, None] = '13b0f2373f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_deepface_face', if_exists=True)
    with op.batch_alter_table('deepface_face', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overlapping', sa.Boolean(), server_default='0', nullable=False))
        batch_op.drop_column('relative_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deepface_face', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relative_path', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('overlapping')

    op.create_table('_alembic_tmp_deepface_face',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('_image_analysis_id', sa.INTEGER(), nullable=True),
    sa.Column('x', sa.INTEGER(), nullable=False),
    sa.Column('y', sa.INTEGER(), nullable=False),
    sa.Column('w', sa.INTEGER(), nullable=False),
    sa.Column('h', sa.INTEGER(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('gender_confidence', sa.FLOAT(), nullable=True),
    sa.Column('race', sa.VARCHAR(), nullable=True),
    sa.Column('race_confidence', sa.FLOAT(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('_performer_id', sa.INTEGER(), nullable=True),
    sa.Column('group', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=14), server_default=sa.text("'DISCOVERED'"), nullable=False),
    sa.Column('overlapping', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['_image_analysis_id'], ['image_analysis.id'], name='fk_image_analysis'),
    sa.ForeignKeyConstraint(['_performer_id'], ['performer.id'], name='fk_performer'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
